dist: trusty
language: python

python:
- 3.4
- 3.5
- 3.5-dev
- 3.6
- 3.6-dev
- 3.7-dev
- nightly

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y -qq python dh-autoreconf squashfs-tools build-essential
- cd ${TRAVIS_BUILD_DIR}

install:
- pip install --upgrade setuptools
- pip install coveralls pytest pytest-runner pycodestyle
- pip install .

script:
- pycodestyle --max-line-length=80 *.py tests/*.py
- coverage run --source brainlearning setup.py pytest

after_success:
- coveralls

deploy:
